### ISSUE TITLE
Cannot find "tasknames.csv" in my unziped motif raw data folder when I processed the raw motif data and ran `sh dedup.sh`

### ISSUE THREAD

**Issue by zerlinwang** [aburns4/MoTIF#2]
Thanks for your amazing work!

I met trouble when I processed the motif dataset:
![image](https://user-images.githubusercontent.com/80957609/208348144-4b4704dd-983d-4184-9ae0-a49ec1fe6adf.png)
I downloaded two raw data folders and unziped them in `MoTIF/task_automation/seq2act/data/motif/raw`.
When I run 'sh dedup.sh', there was an error:
``` Traceback
3061
True
0
Traceback (most recent call last):
  File "all_in_one_motif_preprocess.py", line 678, in <module>
    main()
  File "all_in_one_motif_preprocess.py", line 672, in main
    mysample = MoTIFSample(app, FLAGS.data_dir, trace, 'widget_exception_dims.json')
  File "all_in_one_motif_preprocess.py", line 199, in __init__
    with open(os.path.join(data_dir, 'tasknames.csv')) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/USERNAME/Projects/MoTIF/task_automation/seq2act/data/motif/raw/traces_02_14_21/tasknames.csv'
```

It seems that it was caused by there is not a file named `tasknames.csv` in the raw data folder.
I download the raw data folder again to avoid my download mistake.
Could you help me with it?

**Comment by zerlinwang** [comment]
Thanks for your reply! It helps a lot.
- I want to know what's the difference between raw data folders `traces_02_14_21` and `traces_03_17_21`. The latter has more documents compared to the former. However, in the script file, the former is used by default.
- However when I run `sh dedup.sh` or `sh make_motif_tfrecord.sh` with the already processed jsons, the program displays missing files regardless of whether `traces_02_14_21` or `traces_03_17_21` is used as a parameter.
- sh dedup:
```Traceback
Traceback (most recent call last):
  File "all_in_one_motif_preprocess.py", line 678, in <module>
    main()
  File "all_in_one_motif_preprocess.py", line 669, in main
    app = glob.glob(os.path.join(FLAGS.data_dir, '*', trace))[0]
IndexError: list index out of range
```
- sh make_motif_tfrecord.sh
```Traceback
Traceback (most recent call last):
  File "create_motif_dataset_no_thread.py", line 563, in <module>
    tf.app.run(main)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "create_motif_dataset_no_thread.py", line 545, in main
    create_dataset(FLAGS.dataset, FLAGS.input_dir, FLAGS.output_dir, traces_to_process)
  File "create_motif_dataset_no_thread.py", line 514, in create_dataset
    max_word_num, max_word_length = _process_dimensions(input_dir, output_dir, splits)
  File "create_motif_dataset_no_thread.py", line 188, in _process_dimensions
    max_word_num, max_word_length = _get_data_dimensions(input_dir, splits) # [200, 50]
  File "create_motif_dataset_no_thread.py", line 159, in _get_data_dimensions
    _, max_word_num_one_file, max_word_length_one_file = future.result()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 370, in get_word_statistics
    leaf_nodes = get_view_hierarchy_list(file_path, screen_w, screen_h)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 426, in get_view_hierarchy_list
    vh = _get_view_hierarchy(file_path, MOTIF_SCREEN_WIDTH, MOTIF_SCREEN_HEIGHT)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 441, in _get_view_hierarchy
    data = f.read()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 81, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /home/USERNAME/Projects/MoTIF/task_automation/seq2act/data/motif/raw/traces_02_14_21/com.google.android.youtube/68624722-8469-4a4b-b020-94feee5caff4/view_hierarchies/7bb93e7c-c9c9-473e-be4c-6f49e66d1a89_616_1596487067831.jpg; No such file or directory
```

I downloaded motif raw data twice to exclude my download error.

**Comment by aburns4** [comment]
Hi again, sorry for the delayed response. I think this is occurring because of a version mismatch of `traces_02_14_21` that I was using versus what I open sourced. The open sourced earlier traces folder is what's used for feasibility classification, and it's possible I had multiple internal versions on my machine.

I've been meaning to create a single merged folder for all of the raw data, so let me try to get back to this later this week and fix it for you - I appreciate your patience.

To provide some context for the difference between `traces_02_14_21` and `traces_03_17_21`, they are essentially snapshots of the data at different collection timesteps. 3/17 should be a superset but it's possible I removed some data that makes it not strictly a superset by accident when trying to release only the valid traces. Additionally, there are some traces in the 3/17 folder that were "exploration" action sequences. For these we had users try to find as many unique states within a particular app as possible.

I will try to fix all of this and add some labels to clarify which samples are exploration vs. for train purposes. 

I'll follow up as soon as I can. Again, for Seq2Act modeling at least, I believe you should not need to process the data from the raw folders, since I release the processed json data used to create the tfrecords for their model.

**Comment by zerlinwang** [comment]
> Hi again, sorry for the delayed response. I think this is occurring because of a version mismatch of `traces_02_14_21` that I was using versus what I open sourced. The open sourced earlier traces folder is what's used for feasibility classification, and it's possible I had multiple internal versions on my machine.
> 
> I've been meaning to create a single merged folder for all of the raw data, so let me try to get back to this later this week and fix it for you - I appreciate your patience.
> 
> To provide some context for the difference between `traces_02_14_21` and `traces_03_17_21`, they are essentially snapshots of the data at different collection timesteps. 3/17 should be a superset but it's possible I removed some data that makes it not strictly a superset by accident when trying to release only the valid traces. Additionally, there are some traces in the 3/17 folder that were "exploration" action sequences. For these we had users try to find as many unique states within a particular app as possible.
> 
> I will try to fix all of this and add some labels to clarify which samples are exploration vs. for train purposes.
> 
> I'll follow up as soon as I can. Again, for Seq2Act modeling at least, I believe you should not need to process the data from the raw folders, since I release the processed json data used to create the tfrecords for their model.

Thanks for your patient reply. 
However, File lost error remained even I created the tfrecords by the released processed json.

- sh make_motif_tfrecord.sh
```traceback
Traceback (most recent call last):
  File "create_motif_dataset_no_thread.py", line 563, in <module>
    tf.app.run(main)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "create_motif_dataset_no_thread.py", line 545, in main
    create_dataset(FLAGS.dataset, FLAGS.input_dir, FLAGS.output_dir, traces_to_process)
  File "create_motif_dataset_no_thread.py", line 514, in create_dataset
    max_word_num, max_word_length = _process_dimensions(input_dir, output_dir, splits)
  File "create_motif_dataset_no_thread.py", line 188, in _process_dimensions
    max_word_num, max_word_length = _get_data_dimensions(input_dir, splits) # [200, 50]
  File "create_motif_dataset_no_thread.py", line 159, in _get_data_dimensions
    _, max_word_num_one_file, max_word_length_one_file = future.result()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 370, in get_word_statistics
    leaf_nodes = get_view_hierarchy_list(file_path, screen_w, screen_h)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 426, in get_view_hierarchy_list
    vh = _get_view_hierarchy(file_path, MOTIF_SCREEN_WIDTH, MOTIF_SCREEN_HEIGHT)
  File "/home/USERNAME/Projects/MoTIF/task_automation/seq2act/motif_data_generation/common.py", line 441, in _get_view_hierarchy
    data = f.read()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/USERNAME/Softwares/anaconda3/envs/motif/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 81, in _preread_check
    compat.path_to_str(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /home/USERNAME/Projects/MoTIF/task_automation/seq2act/data/motif/raw/traces_02_14_21/com.google.android.youtube/68624722-8469-4a4b-b020-94feee5caff4/view_hierarchies/7bb93e7c-c9c9-473e-be4c-6f49e66d1a89_616_1596487067831.jpg; No such file or directory
```

**Comment by aburns4** [comment]
Hi Zerlin,

Here https://drive.google.com/file/d/1_yT0QMUyogA-dS0ozBH8Q9Tn5pH9AdvE/view?usp=sharing is a fixed larger version of the MoTIF data. It also includes data from additional traces and the language annotation, which weren't used in the splits for evaluating task automation. 

I'll be updating the READMEs on the main page of the repo to describe metadata provided with each trace as well as update the data generation instructions to reflect this new raw data folder in the coming days.

I was able to successfully process the data (the dedup and tfrecord creation portions) with this new folder of raw data. Please confirm you are able to successfully use it!

**Comment by zerlinwang** [comment]
It works! Thanks again for your patient replies and supports!
